version: '3'

services:

  server:
    image: ubuntu:latest
    container_name: portfolio
    volumes:
      - .:/home
    working_dir: /home
    ports:
      - 80:80
      - 443:443
    command: 'env $(cat .env) server/caddy-linux'
